### ISSUE TITLE
Créer le projet Django et configurer Docker

### ISSUE THREAD

**Issue by hericlibong** [hericlibong/blog_django#1]

**Comment by hericlibong** [comment]
---

### **Critères d'acceptation pour l'issue : Créer le projet Django et configurer Docker**

1. **Configuration Docker :**
   - Un fichier `Dockerfile` est présent à la racine du projet et est configuré pour :
    

- [x]  - Installer Python (version précisée dans le fichier).
- [x]      - Installer Django via un fichier `requirements.txt`.
- [x]      - Copier les fichiers du projet dans le conteneur.
- [x]      - Définir une commande de démarrage appropriée (ex. : `python manage.py runserver`).

   - Un fichier `docker-compose.yml` est configuré pour :
    

- [x]  - Définir un service Django fonctionnel.
- [x]      - Exposer le port nécessaire (ex. : `8000:8000`).
- [x]      - Monter un volume pour permettre le développement en direct sans reconstruire l'image à chaque modification.

2. **Création et structure du projet Django :**
  

- [x]  - Le projet Django est créé dans le conteneur Docker avec la commande `django-admin startproject`.
- [x]    - L’arborescence de base du projet Django est visible dans le volume local.
- [x]    - Le fichier `settings.py` inclut une configuration minimale permettant un fonctionnement de base.

3. **Exécution du conteneur :**
   

- [x] - La commande `docker-compose up` permet de démarrer le conteneur avec succès.
- [x]    - Le serveur Django est accessible via `http://localhost:8000` (ou un port configuré).

4. **Configuration des dépendances :**
  

- [x]  - Un fichier `requirements.txt` contient Django et les dépendances initiales nécessaires.
- [x]    - La commande `pip install -r requirements.txt` fonctionne sans erreur dans le conteneur.

5. **Exclusion des fichiers inutiles :**
  

- [x]  - Un fichier `.gitignore` est en place pour exclure :
- [x]      - Les fichiers liés à Docker (dossiers de volumes).
- [x]      - Les fichiers générés par Django (ex. : `db.sqlite3`).
- [x]      - Les fichiers sensibles de configuration (ex. : `.env`).
- [ ] 

6. **Test de bon fonctionnement :**
  

- [x]  - Un test simple avec `python manage.py runserver` dans le conteneur confirme que Django fonctionne et affiche la page d'accueil par défaut.
- [x]    - Aucune erreur bloquante n’est rencontrée pendant l’exécution.

---

### Points importants à retenir

- [x] - L'ordre des étapes est crucial : **Docker d'abord**, puis **création du projet Django** dans l'environnement Docker.
- [x] - Les fichiers générés par Django (comme `settings.py`) seront ajustés uniquement après avoir été créés dans le conteneur.

**Comment by hericlibong** [comment]
### **Créer un projet Django et configurer Docker : Tutoriel étape par étape**

Dans ce tutoriel, nous allons vous guider à travers le processus complet pour **créer un projet Django** et le configurer avec **Docker**, tout en suivant les meilleures pratiques. L’objectif est de disposer d’une base solide pour un développement rapide, fiable et sécurisé. 

---

## **Introduction**

Le déploiement de Django avec Docker est une solution robuste pour isoler l’environnement de développement et simplifier les déploiements en production. Cette première étape du projet vise à :
1. Configurer Docker pour contenir le serveur Django et la base de données PostgreSQL.
2. Créer un projet Django fonctionnel.
3. Mettre en place un fichier `.env` pour gérer les variables sensibles.
4. Vérifier que tout fonctionne correctement avec un test simple.

---

## **1. Configuration Docker**

### **1.1. Créer les fichiers nécessaires**
À la racine de votre projet, créez trois fichiers principaux :  
- **Dockerfile** : Définit l’environnement pour exécuter Django.
- **docker-compose.yml** : Configure les services (Django et PostgreSQL).
- **requirements.txt** : Liste les dépendances Python nécessaires au projet.

### **1.2. Contenu du fichier `Dockerfile`**
Voici la configuration du `Dockerfile` pour un environnement Django basé sur Python 3.12 :

```dockerfile
# Utiliser l'image officielle de Python
FROM python:3.12-slim

# Installer le client PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier et installer les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste des fichiers
COPY . .

# Rendre un script de gestion exécutable
RUN chmod +x wait-for-postgres.sh

# Exposer le port pour le serveur Django
EXPOSE 8000

# Commande de démarrage par défaut
CMD ["sh", "-c", "./wait-for-postgres.sh db python /app/django_blog/manage.py migrate && python /app/django_blog/manage.py runserver 0.0.0.0:8000"]
```

### **1.3. Contenu du fichier `docker-compose.yml`**
Ce fichier configure deux services : Django (`web`) et PostgreSQL (`db`).

```yaml
version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: >
      sh -c "./wait-for-postgres.sh db python /app/django_blog/manage.py migrate &&
             python /app/django_blog/manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
```

### **1.4. Script `wait-for-postgres.sh`**
Ce script garantit que Django n’essaiera pas de se connecter à PostgreSQL avant que celui-ci soit prêt.

```bash
#!/bin/sh
set -e

host="$1"
shift
cmd="$@"

until PGPASSWORD=$POSTGRES_PASSWORD psql -h "$host" -U "$POSTGRES_USER" -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"
exec $cmd
```

Rendez ce script exécutable :
```bash
chmod +x wait-for-postgres.sh
```

---

## **2. Création et structure du projet Django**

### **2.1. Initialiser le projet Django**
Créez un projet Django directement à l’intérieur du conteneur Docker :
```bash
docker-compose run web django-admin startproject django_blog .
```

### **2.2. Structure attendue**
Après cette commande, voici la structure minimale de votre projet :
```
blog_django/
├── django_blog/
│   ├── django_blog/
│   │   ├── settings.py
│   │   ├── urls.py
│   │   ├── wsgi.py
│   │   └── __init__.py
│   ├── manage.py
├── Dockerfile
├── docker-compose.yml
├── requirements.txt
└── wait-for-postgres.sh
```

---

## **3. Configuration des variables d’environnement**

### **3.1. Fichier `.env`**
Créez un fichier `.env` à la racine pour y stocker les variables sensibles :
```plaintext
SECRET_KEY=django-insecure-6$*kxc&jq^4(1bc3y7u03nx__$#0v-e82194b!xzxyqg02z9vl
DEBUG=True
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_HOST=db
POSTGRES_PORT=5432
```

Ajoutez `.env` à `.gitignore` :
```plaintext
# Environment variables
.env
```

### **3.2. Modifier `settings.py`**
Chargez les variables d’environnement dans le fichier `settings.py` :
```python
from decouple import config

SECRET_KEY = config('SECRET_KEY', default='fallback-secret-key')
DEBUG = config('DEBUG', default=False, cast=bool)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT', cast=int),
    }
}
```

---

## **4. Tests finaux**

1. **Lancer les conteneurs :**
   ```bash
   docker-compose up
   ```

2. **Accéder à Django :**
   - Ouvrez `http://localhost:8000` dans votre navigateur.
   - Vous devriez voir la page par défaut de Django : "The install worked successfully! Congratulations!"

3. **Valider les migrations :**
   - Les migrations initiales doivent être appliquées sans erreur.

---

## **Conclusion**

À ce stade, vous avez un projet Django entièrement fonctionnel, configuré avec Docker et PostgreSQL. Cette base est solide pour ajouter des fonctionnalités supplémentaires comme l’authentification, les modèles de données, et même une API REST. 

Ce tutoriel vous servira de guide pour structurer vos projets futurs en suivant les meilleures pratiques.

**Comment by hericlibong** [comment]
### Configuration Docker revisitée

Pour que ta configuration Docker/Docker Compose se comporte comme un projet Django “classique” (c’est-à-dire que `python manage.py startapp nom_app` crée directement le dossier de l’app à côté de tes autres applications, sans avoir à spécifier de chemins), il faut simplement que le répertoire de travail de ton conteneur (`WORKDIR`) corresponde à l’endroit où se trouve `manage.py`.  

Dans ta structure, on voit que :  
- Le répertoire local **blog_django** contient tous les fichiers Docker (Dockerfile, docker-compose.yml, etc.).  
- Le sous-répertoire **django_blog** contient lui-même **manage.py** et d’autres répertoires (accounts, portfolio, etc.).  

Pour qu’en mode conteneur le comportement soit identique à un usage local standard, l’idée est la suivante :  

1. **On commence** par copier le code dans `/app`.  
2. **On termine** en définissant `WORKDIR /app/django_blog` (là où se trouve `manage.py`).  

De cette façon, quand tu feras un simple :
```bash
docker-compose run --rm web python manage.py startapp nouvelle_app
```
le dossier `nouvelle_app` sera créé à côté de `accounts`, `portfolio`, etc.  

---

## Exemple de configuration adaptée

### Dockerfile

```dockerfile
# Utiliser une image officielle de Python comme base
FROM python:3.12-slim

# Installer le client PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# 1) On place notre répertoire de travail “temporaire” à /app
WORKDIR /app

# 2) On copie le requirements.txt et on installe les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 3) On copie tout le projet (blog_django/*) dans /app
COPY . .

# 4) Rendre le script d’attente exécutable
RUN chmod +x wait-for-postgres.sh

# 5) IMPORTANT : on redéfinit le WORKDIR pour pointer vers le répertoire 
#    qui contient manage.py, c’est-à-dire /app/django_blog
WORKDIR /app/django_blog

# 6) On expose le port
EXPOSE 8000

# 7) Commande de démarrage par défaut
CMD ["sh", "-c", "../wait-for-postgres.sh db python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
```

### docker-compose.yml

Dans ton `docker-compose.yml`, tu peux simplement t’appuyer sur la commande par défaut du Dockerfile. Autrement dit, tu n’es pas obligé de la redéfinir dans `compose` (à moins que tu veuilles la surcharger). L’exemple minimal :

```yaml
version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    # Pas de commande spéciale ici, on laisse le CMD du Dockerfile agir

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
```

> **Remarque** : Si tu préfères garder la commande `migrate && runserver` dans `docker-compose.yml`, il faut juste adapter les chemins pour qu’ils soient cohérents (mais ce n’est pas obligatoire).

---

## Comment ça se comporte ?

- Quand tu fais un `docker-compose up --build`, le service `web` va :  
  1. Copier ton projet dans `/app`.  
  2. **Aller** ensuite dans `/app/django_blog` (là où est `manage.py`).  
  3. Exécuter la commande de démarrage `./wait-for-postgres.sh db python manage.py migrate && python manage.py runserver 0.0.0.0:8000`.  

- Quand tu tapes une commande comme :  
  ```bash
  docker-compose run --rm web python manage.py startapp nouvelle_app
  ```  
  tu seras **déjà** dans `/app/django_blog` dans le conteneur, donc `nouvelle_app` apparaîtra au même niveau que `accounts`, `portfolio`, etc. Tu n’as plus besoin de donner des chemins.

---

**En résumé** : le fait de “descendre” le `WORKDIR` jusqu’au répertoire contenant `manage.py` reproduit le comportement d’un projet Django classique. Tu n’auras plus à préciser le chemin pour créer une nouvelle application, et elle sera générée au bon endroit par défaut.






### Commentaires


Avec cette configuration corrigée et adaptée, tu as maintenant une structure et un comportement alignés avec les pratiques Django traditionnelles tout en tirant parti de Docker. Voici ce que tu peux retenir :

1. **Pourquoi le problème se produisait** :
   - Le `WORKDIR` initial était fixé à `/app`, ce qui faisait que toutes les commandes comme `startapp` utilisaient `/app` comme point de référence, créant ainsi les applications dans des emplacements non souhaités.

2. **Comment cela a été résolu** :
   - En fixant le `WORKDIR` à `/app/django_blog`, où se trouve `manage.py`, on assure que toutes les commandes de gestion (`manage.py`) agissent dans le bon contexte, comme dans une configuration Django classique.

3. **Ce qui a changé dans la pratique** :
   - Lorsqu'on exécute des commandes dans le conteneur, par exemple :
     ```bash
     docker-compose exec web python manage.py startapp my_new_app
     ```
     La nouvelle application `my_new_app` sera correctement créée dans `/app/django_blog`, au même niveau que `accounts`, `portfolio`, etc.

4. **Avantages supplémentaires** :
   - La cohérence entre l'environnement local et le conteneur.
   - Plus besoin de déplacer manuellement les applications ou de modifier les chemins.

Si tu rencontres d'autres comportements inattendus, nous pourrons investiguer plus loin, mais cette configuration devrait garantir une stabilité sur ces aspects fondamentaux. 🚀




---------------------------------------

Exactement, tu as parfaitement raison. Voici les détails pour clarifier cette approche de redirection temporaire du `WORKDIR` :

### Pourquoi ce choix ?
- **WORKDIR temporaire** : Le `WORKDIR /app` initial sert à copier l'intégralité de ton projet dans un répertoire de base bien défini à l'intérieur du conteneur.
- **WORKDIR final** : Le passage à `WORKDIR /app/django_blog` une fois tout copié garantit que toutes les commandes `manage.py` sont exécutées à partir du bon répertoire (celui qui contient `manage.py`).

Cette redirection progressive est une bonne pratique car :
1. **Gestion des chemins dans le conteneur** : Les fichiers sont d'abord centralisés dans `/app`, ce qui permet de gérer tout le projet au même endroit.
2. **Conformité avec Django** : La redirection vers `/app/django_blog` assure que Django fonctionne comme attendu, en prenant `manage.py` comme point de référence.

### Avantages de cette structure :
- **Flexibilité** : En gardant une étape intermédiaire (`/app`), tu peux facilement organiser ou modifier la structure globale de ton projet sans impacter le comportement de Django.
- **Cohérence** : Les fichiers nécessaires à Django (`manage.py`, `accounts`, `portfolio`, etc.) sont toujours dans le bon contexte.
- **Simplification des commandes** : Plus besoin de spécifier de chemins relatifs complexes comme `python /app/django_blog/manage.py`. Tout est pris en charge par la redirection.

### Exemple dans la configuration actuelle
Voici comment cela se traduit dans ton Dockerfile :

```dockerfile
# 1. Travailler temporairement dans /app
WORKDIR /app

# 2. Copier les fichiers dans /app
COPY . .

# 3. Passer au répertoire Django (qui contient manage.py)
WORKDIR /app/django_blog
```

Et dans Docker Compose :
- La commande utilise directement `manage.py` sans spécifier de chemins complexes :
  ```yaml
  command: >
    sh -c "./wait-for-postgres.sh db python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
  ```

### Conclusion
Cette approche combine **organisation claire** et **compatibilité avec Django**, tout en réduisant les erreurs liées aux chemins. Avec cette configuration, tes futures applications, migrations et commandes fonctionneront de manière fluide et cohérente. 🚀




-------------------------------------



Effectivement, tu as raison. La commande définie dans `docker-compose.yml` (section `command`) n'est plus nécessaire si elle est déjà gérée dans le `CMD` du `Dockerfile`. L'idée est de centraliser la configuration pour éviter les redondances ou conflits entre `docker-compose` et le `Dockerfile`.

### Pourquoi supprimer la commande dans `docker-compose.yml` ?
1. **Simplicité** : Le `CMD` dans le `Dockerfile` gère déjà l'exécution de `wait-for-postgres.sh` suivi de la migration et du lancement du serveur.
2. **Éviter les doublons** : Si une commande est définie à la fois dans le `Dockerfile` et dans `docker-compose.yml`, cette dernière prend le dessus, ce qui peut provoquer des incohérences ou surcharger inutilement `docker-compose.yml`.
3. **Maintenabilité** : En laissant le `Dockerfile` gérer les commandes par défaut, tu rends le fichier `docker-compose.yml` plus léger et plus lisible.

### Que faire dans ce cas ?
Il suffit de retirer la section `command` de `docker-compose.yml`, comme ceci :

#### Fichier `docker-compose.yml` après modification
```yaml
version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    # La commande est maintenant gérée dans le Dockerfile, donc inutile ici.

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
```

### Où se trouve la commande maintenant ?
Le `CMD` dans le `Dockerfile` prend entièrement le relais pour exécuter la commande par défaut au démarrage du conteneur `web`. Par exemple :

#### `Dockerfile`
```dockerfile
CMD ["sh", "-c", "./wait-for-postgres.sh db python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
```

### Résultat attendu
- Lors de l'exécution de `docker-compose up`, la commande définie dans le `Dockerfile` sera automatiquement exécutée.
- Plus besoin de maintenir ou de redéfinir cette commande dans `docker-compose.yml`.

Cela réduit le risque d'erreur et rend ta configuration Docker plus propre et maintenable.
